name: bright
channels:
- pytorch
- defaults
dependencies:
- python=3.8
- pytorch=1.13.1
- cudatoolkit=11.7
- scipy
- pip
- pip:
  - dominate==2.6.0
  - torchvision==0.14.1
  - Pillow==8.0.1
  - numpy==1.19.2
  - visdom==0.1.8
  - wandb==0.12.18

